export type Language = 'en' | 'kn' | 'sa';

export const Strings = {
    en: {
        appName: "VedaKal",
        tithi: "Tithi",
        nakshatra: "Nakshatra",
        vara: "Vara",
        yoga: "Yoga",
        sunrise: "Sunrise",
        sunset: "Sunset",
        selectCity: "Select City",
        today: "Today",
        changeLanguage: "Change Language",
        searchCity: "Search City...",
        close: "Close",
        loading: "Loading...",
        karana: "Karana",
        samvatsara: "Samvatsara",
        ritu: "Ritu",
        ayana: "Ayana",
        endsAt: "Ends at",
        rahuKalam: "Rahu Kalam",
        yamaganda: "Yamaganda",
        gulikaKalam: "Gulika Kalam",
        sunTimings: "Sun Timings",
        inauspiciousPeriods: "Inauspicious Periods",
        months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"]
    },
    kn: {
        appName: "ವೇದಕಾಲ (VedaKal)",
        tithi: "ತಿಥಿ",
        nakshatra: "ನಕ್ಷತ್ರ",
        vara: "ವಾರ",
        yoga: "ಯೋಗ",
        sunrise: "ಸೂರ್ಯೋದಯ",
        sunset: "ಸೂರ್ಯಾಸ್ತ",
        selectCity: "ನಗರವನ್ನು ಆರಿಸಿ",
        today: "ಇಂದು",
        changeLanguage: "ಭಾಷೆಯನ್ನು ಬದಲಾಯಿಸಿ",
        searchCity: "ನಗರವನ್ನು ಹುಡುಕಿ...",
        close: "ಮುಚ್ಚಿ",
        loading: "ಲೋಡ್ ಆಗುತ್ತಿದೆ...",
        karana: "ಕರಣ",
        samvatsara: "ಸಂವತ್ಸರ",
        ritu: "ಋತು",
        ayana: "ಅಯನ",
        endsAt: "ಸಮಾಪ್ತಿ",
        rahuKalam: "ರಾಹುಕಾಲ",
        yamaganda: "ಯಮಗಂಡ",
        gulikaKalam: "ಗುಳಿಕ ಕಾಲ",
        sunTimings: "ಸೂರ್ಯ ಸಮಯ",
        inauspiciousPeriods: "ಅಶುಭ ಸಮಯಗಳು",
        months: ["ಜನವರಿ", "ಫೆಬ್ರವರಿ", "ಮಾರ್ಚ್", "ಏಪ್ರಿಲ್", "ಮೇ", "ಜೂನ್", "ಜುಲೈ", "ಆಗಸ್ಟ್", "ಸೆಪ್ಟೆಂಬರ್", "ಅಕ್ಟೋಬರ್", "ನವೆಂಬರ್", "ಡಿಸೆಂಬರ್"]
    },
    sa: {
        appName: "वेदकाल (VedaKal)",
        tithi: "तिथिः",
        nakshatra: "नक्षत्रम्",
        vara: "वासरः",
        yoga: "योगः",
        sunrise: "सूर्योदयः",
        sunset: "सूर्यास्तः",
        selectCity: "नगरं चिनोतु",
        today: "अद्य",
        changeLanguage: "भाषां परिवर्तयतु",
        searchCity: "नगरं अन्विष्यतु...",
        close: "पिधत्त",
        loading: "प्रतीक्ष्यताम्...",
        karana: "करण",
        samvatsara: "संवत्सर",
        ritu: "ऋतु",
        ayana: "अयन",
        endsAt: "समाप्ति",
        rahuKalam: "राहुकाल",
        yamaganda: "यमगण्ड",
        gulikaKalam: "गुलिक काल",
        sunTimings: "सूर्य समयः",
        inauspiciousPeriods: "अशुभ समयाः",
        months: ["जनवरी", "फरवरी", "मार्च", "अप्रैल", "मई", "जून", "जुलाई", "अगस्त", "सितम्बर", "अक्तूबर", "नवम्बर", "दिसम्बर"]
    }
};
